### ISSUE TITLE
ValueError: Not a boolean

### ISSUE THREAD

**Issue by Aintgood** [souravrs999/FaucetCryptoBot#11]
Got issue while run the bot, i no have idea what happened with this log.

> Traceback (most recent call last):
  File "bot.py", line 27, in <module>
    faucet_bot()
  File "bot.py", line 5, in faucet_bot
    bot = FaucetCryptoBot()
  File "C:\Users\Burok\Desktop\FaucetCryptoBot-main\FaucetCryptoBot\fcbot.py", line 19, in __init__
    self.debug = self._configParser()[5]
  File "C:\Users\Burok\Desktop\FaucetCryptoBot-main\FaucetCryptoBot\fcbot.py", line 117, in _configParser
    debug = config.getboolean("Misc", "debug")
  File "c:\users\burok\appdata\local\programs\python\python38-32\lib\configparser.py", line 828, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
  File "c:\users\burok\appdata\local\programs\python\python38-32\lib\configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "c:\users\burok\appdata\local\programs\python\python38-32\lib\configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "c:\users\burok\appdata\local\programs\python\python38-32\lib\configparser.py", line 1163, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: <if you want to write errors to the console True or False>

**Comment by souravrs999** [comment]
Probably messed up the config.cfg file the boolean value given to debug field should be either True or False it cant accept other values. That might be the issue.
