### ISSUE TITLE
Invalid Access to memory

### ISSUE THREAD

**Issue by Dexenthes** [souravrs999/FaucetCryptoBot#18]
Hi, 

I'm just about to start the bot but I keep running into this problem, see below. I feel like there's something simple I'm missing? I haven't been able to find a solution to this invalid memory access. 

Traceback (most recent call last):
  File "D:\FaucetCryptoBot-main\bot.py", line 27, in <module>
    faucet_bot()
  File "D:\FaucetCryptoBot-main\bot.py", line 5, in faucet_bot
    bot = FaucetCryptoBot()
  File "D:\FaucetCryptoBot-main\FaucetCryptoBot\fcbot.py", line 35, in __init__
    self.driver = Chrome(options=self._get_opts(), executable_path=self.driver_path)
  File "C:\Users\joe\AppData\Local\Programs\Python\Python39\Scripts\env\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\joe\AppData\Local\Programs\Python\Python39\Scripts\env\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "c:\users\joe\appdata\local\programs\python\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\joe\appdata\local\programs\python\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 998] Invalid access to memory location

**Comment by Dexenthes** [comment]
Nevermind, solved it by switching to another pc
