### ISSUE TITLE
Bot crashed

### ISSUE THREAD

**Issue by dederaditya** [souravrs999/FaucetCryptoBot#9]
```
Traceback (most recent call last):
  File "bot.py", line 27, in <module>
    faucet_bot()
  File "bot.py", line 5, in faucet_bot
    bot = FaucetCryptoBot()
  File "/root/FaucetCryptoBot/FaucetCryptoBot/fcbot.py", line 35, in __init__
    self.driver = Chrome(options=self._get_opts(), executable_path=self.driver_path)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 98, in start
    self.assert_process_still_running()
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
    % (self.path, return_code)
selenium.common.exceptions.WebDriverException: Message: Service /usr/bin/chromium-browser unexpectedly exited. Status code was: 1

```

Any idea?

**Comment by souravrs999** [comment]
I think the issues with your chromium browser is this happening often

**Comment by dederaditya** [comment]
Is it because I'm running another program with it? I rarely use linux

**Comment by souravrs999** [comment]
> Is it because I'm running another program with it? I rarely use linux

Are you running any program that uses the browser as well?

**Comment by dederaditya** [comment]
> > Is it because I'm running another program with it? I rarely use linux
> 
> Are you running any program that uses the browser as well?

Yes another program, I will try if it's done
